# The Docker image that will be used to build your app
image: alpine:latest

# Functions that should be executed before the build script is run
before_script:
- apk update
- apk add doxygen
- apk add ttf-freefont graphviz

pages:
  script:
    - doxygen doxygen/Doxyfile
    - mv doxygen/documentation/html/ public/
    - echo "Documentation is deployed for the current library version."
    - doxygen doxygen/Doxyfile
    - mv doxygen/documentation/html/ public/0.1.0/
    - echo "Documentation is deployed for the library version 0.1.0."
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
